version: "3.9"  # optional since v1.27.0
services:
  pg:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'application'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    volumes:
      - ./database-data:/var/lib/mysql
    ports:
      - 3306:3306
  pg-test:
    container_name: db-test
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'application-test'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - 3307:3306